---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: tsuki-os
# description will be included in the image's metadata
description: Simi's Custom Atomic Hyprland Rice.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 44

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # Add RPMFusion
  - type: bling
    install:
      - dconf-update-service

  # Install Brew
  - type: brew
    nofile-limits: true
    brew-analytics: false

  # Initial Package Management
  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      copr:
        - lionheartp/Hyprland
        - atim/starship

    # Packages That Should Be Installed
    install:
      packages:
        # Ui/UX
        - ags
        - astal
        - awww

        # Hyprland
        - hyprland
        - hypridle
        - hyprlock
        - hyprcursor
        - hyprshot

        # Theming
        - kvantum
        - nwg-look
        - qt5ct
        - qt6ct

        # Management
        - ghostty

        # Audio
        - pipewire
        - pipewire-pulseaudio
        - wireplumber
        - mopidy
        - mopidy-mpd

        # System Tools
        - uv
        - git
        - curl
        - wget
        - unzip

        # Fun Tools
        - fastfetch
        - cava
        - ncmpcpp

        # Utilities
        - nautilus # File Manager
        - satty # Screenshot

        # Network
        - NetworkManager
        - xdg-desktop-portal-hyprland
        - matugen

        # Terminal Experience
        - starship
        - neovim

    # Packages That Should Be Removed
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  # Default Flatpaks
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        # install: # system flatpaks we want all users to have and not remove

      - scope: user # Also add Flathub user repo, but no user packages

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: user
        # FlatHub is used by default.
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe

          # Gaming Utilities
          - com.valvesoftware.Steam
          - com.vysp3r.ProtonPlus

          # Communication Utilities
          - com.discordapp.Discord

          # Media
          - com.spotify.Client

          # Tools
          - com.visualstudio.code

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
